import { useEffect, useState } from "react";
import { BellRing, CalendarDays, ChevronRight, Inbox, MessageSquare, Phone, ReceiptText, UserRound } from "lucide-react";
import CustomerNav from "@/components/CustomerNav";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { toast } from "sonner";
import { MotionItem, MotionReveal, MotionStagger } from "@/components/MotionReveal";

export function MyBookings() {
  const { isAuthenticated } = useAuth();
  const bookings = trpc.bookings.mine.useQuery(undefined, { enabled: isAuthenticated });
  const cancel = trpc.bookings.cancel.useMutation({ onSuccess: () => { toast.success("Booking cancelled."); bookings.refetch(); }, onError: error => toast.error(error.message) });
  return <AccountShell title="My bookings" subtitle="Your confirmed and recent plans, generated from real QueueSync activity." icon={CalendarDays}>{!isAuthenticated ? <SignInPrompt /> : bookings.isLoading ? <BookingSkeleton /> : bookings.data?.length ? <MotionStagger className="space-y-3">{bookings.data.map(({ booking, business, resource }) => <MotionItem key={booking.id}><article className="surface-card flex flex-col gap-4 rounded-[1.3rem] p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 gap-4"><span className="signal-orb h-11 w-11 shrink-0"><CalendarDays className="h-4 w-4" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-bold">{business.name}</p><Badge variant={booking.status === "confirmed" ? "default" : "secondary"} className="capitalize">{booking.status}</Badge></div><p className="mt-1.5 text-sm leading-6 text-muted-foreground">{resource.name} · {new Date(booking.startsAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</p></div></div>{["pending", "confirmed"].includes(booking.status) ? <Button variant="outline" size="sm" loading={cancel.isPending} onClick={() => cancel.mutate({ bookingId: booking.id })}>{cancel.isPending ? "Cancelling…" : "Cancel booking"}</Button> : <Button asChild variant="ghost" size="sm"><Link href={`/business/${business.id}`}>View business <ChevronRight className="h-3.5 w-3.5" /></Link></Button>}</article></MotionItem>)}</MotionStagger> : <Empty icon={CalendarDays} text="No bookings yet" detail="When you reserve an available time, it will appear here with its current status." action="Explore businesses" href="/explore" />}</AccountShell>;
}

export function Notifications() {
  const { isAuthenticated } = useAuth();
  const notifications = trpc.notifications.list.useQuery(undefined, { enabled: isAuthenticated });
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => notifications.refetch() });
  return <AccountShell title="Notifications" subtitle="Booking and live-queue changes are recorded here when they happen." icon={BellRing}>{!isAuthenticated ? <SignInPrompt /> : notifications.isLoading ? <BookingSkeleton /> : notifications.data?.length ? <MotionStagger className="space-y-3">{notifications.data.map(notification => <MotionItem key={notification.id}><button type="button" onClick={() => !notification.readAt && markRead.mutate({ notificationId: notification.id })} className={`surface-card w-full rounded-[1.3rem] p-5 text-left transition-all duration-200 hover:-translate-y-px hover:border-primary/30 ${notification.readAt ? "" : "border-primary/30 bg-primary/5"}`}><div className="flex items-start gap-3.5"><span className={`mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-lg ${notification.readAt ? "bg-secondary text-muted-foreground" : "bg-primary text-primary-foreground"}`}><Inbox className="h-3.5 w-3.5" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-bold capitalize">{notification.title}</p>{!notification.readAt ? <span className="inline-flex items-center gap-1 text-[10px] font-extrabold uppercase tracking-[.12em] text-primary"><i className="status-dot" />New</span> : null}</div><p className="mt-1.5 text-sm leading-6 text-muted-foreground">{notification.message}</p><p className="mt-3 text-xs font-semibold text-muted-foreground">{new Date(notification.createdAt).toLocaleString()}</p></div></div></button></MotionItem>)}</MotionStagger> : <Empty icon={Inbox} text="No notifications yet" detail="Queue and booking events will appear here as you use the service." />}</AccountShell>;
}

export function ProfileSettings() {
  const { isAuthenticated, refresh } = useAuth();
  const profile = trpc.profile.get.useQuery(undefined, { enabled: isAuthenticated });
  const [displayName, setDisplayName] = useState("");
  const [phone, setPhone] = useState("");
  const update = trpc.profile.update.useMutation({ onSuccess: () => { toast.success("Profile settings saved."); profile.refetch(); refresh(); }, onError: error => toast.error(error.message) });
  useEffect(() => { if (profile.data) { setDisplayName(profile.data.displayName || ""); setPhone(profile.data.phone || ""); } }, [profile.data]);
  return <AccountShell title="Profile & settings" subtitle="Keep the account details that support your QueueSync experience current." icon={UserRound}>{!isAuthenticated ? <SignInPrompt /> : <form className="grid max-w-xl gap-5" onSubmit={event => { event.preventDefault(); update.mutate({ displayName, phone }); }}><FormLabel icon={UserRound} label="Display name"><Input value={displayName} onChange={event => setDisplayName(event.target.value)} placeholder="Your name" className="field-polish h-11" /></FormLabel><FormLabel icon={Phone} label="Phone number"><Input value={phone} onChange={event => setPhone(event.target.value)} placeholder="Optional contact number" className="field-polish h-11" /></FormLabel><div className="mt-2 flex flex-wrap items-center gap-3"><Button loading={update.isPending}>{update.isPending ? "Saving settings…" : "Save settings"}</Button><p className="text-xs text-muted-foreground">Your changes are saved to your account record.</p></div></form>}</AccountShell>;
}

function AccountShell({ title, subtitle, icon: Icon, children }: { title: string; subtitle: string; icon: typeof CalendarDays; children: React.ReactNode }) { return <div className="min-h-screen overflow-x-clip mesh-bg"><CustomerNav /><main className="container max-w-5xl py-10 sm:py-14"><MotionReveal><div className="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-end"><div><div className="section-kicker">Customer space</div><h1 className="display-font mt-4 text-[clamp(2.4rem,5vw,3.8rem)] font-bold leading-none tracking-[-.065em]">{title}</h1><p className="mt-4 max-w-xl leading-7 text-muted-foreground">{subtitle}</p></div><span className="signal-orb h-12 w-12"><Icon className="h-5 w-5" /></span></div></MotionReveal><MotionReveal delay={0.06} className="mt-8"><section className="surface-card rounded-[1.8rem] p-5 sm:p-7">{children}</section></MotionReveal></main></div>; }
function SignInPrompt() { return <div className="empty-illustration py-10 text-center"><span className="signal-orb mx-auto h-14 w-14"><MessageSquare className="h-5 w-5" /></span><p className="mt-5 font-bold">Sign in to see your QueueSync activity.</p><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-muted-foreground">Your bookings, profile details, and notification history are kept in your authenticated account.</p><Button className="mt-6" onClick={() => startLogin()}>Sign in</Button></div>; }
function Empty({ icon: Icon, text, detail, action, href }: { icon: typeof Inbox; text: string; detail: string; action?: string; href?: string }) { return <div className="empty-illustration py-10 text-center sm:py-14"><span className="signal-orb mx-auto h-14 w-14"><Icon className="h-5 w-5" /></span><p className="mt-5 text-lg font-bold">{text}</p><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-muted-foreground">{detail}</p>{action && href ? <Button asChild className="mt-6"><Link href={href}>{action}<ChevronRight className="h-4 w-4" /></Link></Button> : null}</div>; }
function BookingSkeleton() { return <div className="space-y-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-24 animate-pulse rounded-[1.3rem] bg-muted" />)}</div>; }
function FormLabel({ icon: Icon, label, children }: { icon: typeof UserRound; label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-bold"><span className="flex items-center gap-2 text-muted-foreground"><Icon className="h-3.5 w-3.5 text-primary" />{label}</span>{children}</label>; }
