import { useEffect, useState } from "react";
import { CalendarDays, ChevronRight, Inbox, MessageSquare, ReceiptText } from "lucide-react";
import CustomerNav from "@/components/CustomerNav";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { toast } from "sonner";

export function MyBookings() {
  const { isAuthenticated } = useAuth();
  const bookings = trpc.bookings.mine.useQuery(undefined, { enabled: isAuthenticated });
  const cancel = trpc.bookings.cancel.useMutation({ onSuccess: () => { toast.success("Booking cancelled."); bookings.refetch(); }, onError: error => toast.error(error.message) });
  return <AccountShell title="My bookings" subtitle="Every booking below comes from your QueueSync activity.">{!isAuthenticated ? <SignInPrompt /> : bookings.isLoading ? <div className="h-28 animate-pulse rounded-2xl bg-muted" /> : bookings.data?.length ? <div className="space-y-3">{bookings.data.map(({ booking, business, resource }) => <div key={booking.id} className="flex flex-col gap-4 rounded-2xl border bg-card p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="font-bold">{business.name}</p><Badge variant="secondary" className="capitalize">{booking.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{resource.name} · {new Date(booking.startsAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</p></div>{["pending", "confirmed"].includes(booking.status) ? <Button variant="outline" size="sm" disabled={cancel.isPending} onClick={() => cancel.mutate({ bookingId: booking.id })}>Cancel</Button> : <Link href={`/business/${business.id}`}><Button variant="ghost" size="sm">View business <ChevronRight className="ml-1 h-3.5 w-3.5" /></Button></Link>}</div>)}</div> : <Empty icon={CalendarDays} text="No bookings yet" detail="When you reserve an available slot, it will appear here." action="Explore businesses" href="/explore" />}</AccountShell>;
}

export function Notifications() {
  const { isAuthenticated } = useAuth();
  const notifications = trpc.notifications.list.useQuery(undefined, { enabled: isAuthenticated });
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => notifications.refetch() });
  return <AccountShell title="Notifications" subtitle="Updates are generated by real booking and queue events.">{!isAuthenticated ? <SignInPrompt /> : notifications.isLoading ? <div className="h-28 animate-pulse rounded-2xl bg-muted" /> : notifications.data?.length ? <div className="space-y-3">{notifications.data.map(notification => <button type="button" key={notification.id} onClick={() => !notification.readAt && markRead.mutate({ notificationId: notification.id })} className={`w-full rounded-2xl border p-5 text-left transition ${notification.readAt ? "bg-card" : "border-primary/25 bg-primary/5"}`}><div className="flex items-start gap-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-primary" /><div><p className="font-bold capitalize">{notification.title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{notification.message}</p><p className="mt-3 text-xs text-muted-foreground">{new Date(notification.createdAt).toLocaleString()}</p></div></div></button>)}</div> : <Empty icon={Inbox} text="No notifications yet" detail="Queue and booking updates will be collected here as you use the service." />}</AccountShell>;
}

export function ProfileSettings() {
  const { isAuthenticated, refresh } = useAuth();
  const profile = trpc.profile.get.useQuery(undefined, { enabled: isAuthenticated });
  const [displayName, setDisplayName] = useState("");
  const [phone, setPhone] = useState("");
  const update = trpc.profile.update.useMutation({ onSuccess: () => { toast.success("Profile settings saved."); profile.refetch(); refresh(); }, onError: error => toast.error(error.message) });
  useEffect(() => { if (profile.data) { setDisplayName(profile.data.displayName || ""); setPhone(profile.data.phone || ""); } }, [profile.data]);
  return <AccountShell title="Profile & settings" subtitle="Keep your QueueSync account details current.">{!isAuthenticated ? <SignInPrompt /> : <form className="grid max-w-lg gap-5" onSubmit={event => { event.preventDefault(); update.mutate({ displayName, phone }); }}><FormLabel label="Display name"><Input value={displayName} onChange={event => setDisplayName(event.target.value)} placeholder="Your name" /></FormLabel><FormLabel label="Phone number"><Input value={phone} onChange={event => setPhone(event.target.value)} placeholder="Optional contact number" /></FormLabel><Button className="w-fit" disabled={update.isPending}>{update.isPending ? "Saving…" : "Save settings"}</Button></form>}</AccountShell>;
}

function AccountShell({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen mesh-bg"><CustomerNav /><main className="container max-w-4xl py-10 sm:py-14"><p className="text-sm font-bold text-primary">Customer space</p><h1 className="display-font mt-2 text-4xl font-bold tracking-[-.04em]">{title}</h1><p className="mt-3 text-muted-foreground">{subtitle}</p><section className="mt-8 glass rounded-[1.75rem] border p-5 shadow-xl shadow-slate-950/[.03] sm:p-7">{children}</section></main></div>; }
function SignInPrompt() { return <div className="py-10 text-center"><MessageSquare className="mx-auto h-6 w-6 text-primary" /><p className="mt-4 font-semibold">Sign in to see your QueueSync activity.</p><Button className="mt-5" onClick={() => startLogin()}>Sign in</Button></div>; }
function Empty({ icon: Icon, text, detail, action, href }: { icon: typeof Inbox; text: string; detail: string; action?: string; href?: string }) { return <div className="py-10 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-secondary text-primary"><Icon className="h-5 w-5" /></span><p className="mt-4 font-semibold">{text}</p><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-muted-foreground">{detail}</p>{action && href ? <Link href={href}><Button className="mt-5">{action}</Button></Link> : null}</div>; }
function FormLabel({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-semibold">{label}{children}</label>; }
