import React, { useMemo, useState } from "react";
import { Link } from "wouter";
import { Activity, ArrowRight, BarChart3, Building2, CalendarCheck, CircleCheck, Clock3, Gauge, MapPin, Radio, Search, SlidersHorizontal, Sparkles, UsersRound, Zap } from "lucide-react";
import CustomerNav, { HomeFeatures } from "@/components/CustomerNav";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import LiveFlow from "@/components/LiveFlow";
import { useAuth } from "@/_core/hooks/useAuth";

const flow = [
  ["01", "Discover", "Find a business and see genuine availability."],
  ["02", "Book or join", "Reserve a slot or enter its live queue."],
  ["03", "Track live", "Follow your position without refreshing."],
  ["04", "Operate", "Merchants call, serve, and complete work."],
  ["05", "Complete", "Every lifecycle change is stored with a timestamp."],
  ["06", "Learn", "Real operations create the analytics view."],
] as const;

const businessTypes = ["Gaming café", "Salon", "Clinic", "Restaurant", "Co-working", "Sports facility"];

export default function Home() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("");
  const [availableOnly, setAvailableOnly] = useState(false);
  const [openNow, setOpenNow] = useState(false);
  const filters = useMemo(() => ({ query: query || undefined, category: category || undefined, availableOnly, openNow }), [query, category, availableOnly, openNow]);
  const businesses = trpc.businesses.list.useQuery(filters);
  const categories = Array.from(new Set((businesses.data ?? []).map(item => item.business.category))).slice(0, 5);
  const featured = businesses.data?.[0];

  return <div className="min-h-screen overflow-x-clip mesh-bg"><CustomerNav /><main>
    <section className="container grid items-center gap-8 py-10 sm:gap-10 sm:py-14 lg:grid-cols-[minmax(0,1.05fr)_minmax(22rem,.95fr)] lg:gap-14 lg:py-20 xl:py-24">
      <div className="min-w-0 soft-rise">
        <div className="inline-flex max-w-full items-center gap-2 rounded-full border bg-card/75 px-3 py-1.5 text-xs font-bold text-primary shadow-sm"><Sparkles className="h-3.5 w-3.5 shrink-0" />Live availability, without the wait</div>
        <h1 className="display-font mt-5 max-w-3xl break-words text-[clamp(2.45rem,10vw,5.9rem)] font-bold leading-[.98] tracking-[-.06em]">Local service time, <span className="text-primary">made visible.</span></h1>
        <p className="mt-5 max-w-xl text-[clamp(1rem,3.8vw,1.18rem)] leading-7 text-muted-foreground sm:leading-8">Find genuine business availability, book ahead, or join a live queue that stays current wherever you are.</p>
        <div className="mt-5"><LiveFlow /></div>
        <div className="mt-7 grid gap-3 sm:flex sm:flex-wrap"><Button size="lg" className="w-full rounded-xl bg-[#16c79a] font-bold text-slate-950 shadow-xl shadow-emerald-500/25 hover:bg-[#2cdbb0] sm:w-auto" onClick={() => document.getElementById("discover")?.scrollIntoView({ behavior: "smooth", block: "start" })}>Explore businesses <ArrowRight className="ml-2 h-4 w-4" /></Button><Button size="lg" className="w-full rounded-xl border border-primary/45 bg-card/85 font-bold text-foreground shadow-lg shadow-slate-950/10 hover:bg-secondary sm:w-auto" onClick={() => window.location.assign("/merchant")}>Run your operations</Button></div>
        <div className="mt-8 sm:mt-10"><HomeFeatures /></div>
      </div>
      <div className="space-y-4"><ProductPreview featured={featured} /><MerchantOperationsPreview /></div>
    </section>

    <section className="border-y border-border/70 bg-card/35 py-10 sm:py-14"><div className="container"><SectionEyebrow text="How QueueSync works" /><div className="mt-3 flex flex-col justify-between gap-4 md:flex-row md:items-end"><h2 className="display-font max-w-2xl text-[clamp(1.9rem,6vw,3.25rem)] font-bold tracking-[-.045em]">One operational thread, from first search to useful insight.</h2><p className="max-w-sm text-sm leading-6 text-muted-foreground">The product is built around real records, real state transitions, and live updates instead of simulated operational data.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{flow.map(([number, title, detail]) => <article key={number} className="rounded-2xl border bg-card p-4 shadow-sm"><p className="text-xs font-bold tracking-[.16em] text-primary">{number}</p><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p></article>)}</div></div></section>

    <section className="container grid gap-5 py-10 sm:py-14 lg:grid-cols-2 lg:gap-7"><ExperienceCard eyebrow="Customer experience" icon={UsersRound} title="Confidence before you leave." detail="Customers discover a business, choose an available resource, book a valid slot, and watch their genuine queue position update automatically." actions={["Explore availability", "Reserve a time", "Follow the queue"]} href="/explore" action="Explore customer flow" /><ExperienceCard eyebrow="Merchant experience" icon={Gauge} title="Operations stay in one place." detail="Merchants manage resources, schedule slots, call the next customer, record service milestones, and review data that the operation actually produced." actions={["Set up resources", "Run the queue", "Review analytics"]} href="/merchant" action="Open merchant workspace" /></section>

    <section className="container pb-10 sm:pb-14"><div className="overflow-hidden rounded-[1.75rem] border bg-card shadow-xl shadow-slate-950/[.04]"><div className="grid gap-6 p-5 sm:p-7 lg:grid-cols-[.9fr_1.1fr] lg:p-9"><div><SectionEyebrow text="Real-time, explained" /><h2 className="display-font mt-3 text-[clamp(1.8rem,5vw,3rem)] font-bold tracking-[-.045em]">The queue moves once. Every connected view sees it.</h2><p className="mt-4 max-w-md leading-7 text-muted-foreground">QueueSync broadcasts tenant-scoped booking, resource, notification, and queue updates through the backend. The customer and merchant views invalidate their real records—there is no decorative timer pretending to be live.</p><div className="mt-6 rounded-2xl bg-secondary p-4"><LiveFlow /><p className="mt-3 text-sm font-semibold">Connected views refresh from the same operational event.</p></div></div><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1"><SyncStep icon={Radio} title="Customer view" detail="Position, wait context, and notifications." /><SyncStep icon={Activity} title="Queue event" detail="Called, in-service, completed, no-show, or cancelled." /><SyncStep icon={BarChart3} title="Merchant insight" detail="Persisted activity becomes useful analytics." /></div></div></div></section>

    <section id="discover" className="container scroll-mt-24 pb-10 sm:pb-14"><div className="rounded-[1.75rem] border bg-card/75 p-4 shadow-xl shadow-slate-950/[.03] sm:p-6 lg:p-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><SectionEyebrow text="Business discovery" /><h2 className="display-font mt-2 text-[clamp(1.8rem,5vw,2.5rem)] font-bold tracking-[-.04em]">Find time that works for you.</h2></div><label className="flex w-full items-center gap-2 rounded-xl border bg-background px-3 py-2 text-sm text-muted-foreground lg:max-w-sm"><Search className="h-4 w-4 shrink-0" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Business, category, or area" className="h-7 min-w-0 border-0 bg-transparent p-0 shadow-none focus-visible:ring-0" /></label></div><div className="mt-5 flex flex-wrap gap-2"><Button size="sm" variant={category === "" ? "default" : "outline"} onClick={() => setCategory("")}>All</Button>{categories.map(item => <Button key={item} size="sm" variant={category === item ? "default" : "outline"} onClick={() => setCategory(item)}>{item}</Button>)}<Button size="sm" variant={availableOnly ? "default" : "outline"} onClick={() => setAvailableOnly(value => !value)}><SlidersHorizontal className="mr-1.5 h-3.5 w-3.5" />Available now</Button><Button size="sm" variant={openNow ? "default" : "outline"} onClick={() => setOpenNow(value => !value)}><Clock3 className="mr-1.5 h-3.5 w-3.5" />Open now</Button></div><BusinessGrid loading={businesses.isLoading} items={businesses.data ?? []} /></div></section>

    <section className="border-y border-border/70 bg-secondary/45 py-10 sm:py-14"><div className="container"><SectionEyebrow text="Made for service operations" /><h2 className="display-font mt-2 max-w-2xl text-[clamp(1.8rem,5vw,2.8rem)] font-bold tracking-[-.045em]">One system, adaptable to the way a local business serves people.</h2><div className="mt-6 flex flex-wrap gap-2">{businessTypes.map(type => <span key={type} className="rounded-full border bg-card px-4 py-2 text-sm font-semibold text-muted-foreground">{type}</span>)}</div></div></section>

    <section className="container py-10 sm:py-14"><div className="rounded-[1.75rem] bg-primary px-5 py-8 text-primary-foreground shadow-2xl shadow-primary/20 sm:px-8 sm:py-12"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-bold text-primary-foreground/75">Ready when your operation is</p><h2 className="display-font mt-2 max-w-2xl text-[clamp(2rem,6vw,3.6rem)] font-bold leading-none tracking-[-.05em]">Make the next wait visible.</h2><p className="mt-4 max-w-xl leading-7 text-primary-foreground/80">Start with your real business configuration. QueueSync will build the operational view from what actually happens next.</p></div><div className="grid gap-3 sm:flex"><Button asChild size="lg" variant="secondary" className="w-full rounded-xl sm:w-auto"><Link href="/merchant">Set up a business</Link></Button><Button asChild size="lg" variant="outline" className="w-full border-primary-foreground/30 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground sm:w-auto"><Link href="/explore">Explore QueueSync</Link></Button></div></div></div></section>
  </main><footer className="border-t border-border/70 bg-card/45"><div className="container flex flex-col gap-3 py-6 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><BrandFooter /><p>Real bookings, queues, and operations—kept in sync.</p></div></footer></div>;
}

function ProductPreview({ featured }: { featured: { business: { id: string; name: string; category: string; area: string | null; address: string | null }; resourceCount: number } | undefined }) {
  return <div className="soft-rise min-w-0 [animation-delay:80ms]"><div className="rounded-[1.75rem] border bg-card/90 p-4 shadow-2xl shadow-primary/10 sm:p-5"><div className="flex items-center justify-between border-b pb-4"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-primary">Product preview</p><p className="mt-1 font-semibold">Live operations, not a mockup</p></div><span className="h-3 w-3 rounded-full bg-[var(--live)] ring-4 ring-[color-mix(in_srgb,var(--live)_18%,transparent)]" /></div>{featured ? <div className="mt-4 space-y-3"><div className="rounded-2xl bg-secondary p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Live business record</p><p className="mt-1 truncate text-lg font-bold">{featured.business.name}</p><p className="mt-1 text-sm text-muted-foreground">{featured.business.area || featured.business.address || featured.business.category}</p></div><Badge variant="secondary">{featured.business.category}</Badge></div></div><div className="grid gap-3 sm:grid-cols-2"><PreviewMetric icon={Building2} label="Configured resources" value={`${featured.resourceCount}`} detail="From this business record" /><PreviewMetric icon={CalendarCheck} label="Customer actions" value="Book or join" detail="Validated by the backend" /></div><Link href={`/business/${featured.business.id}`} className="flex min-h-12 items-center justify-between rounded-xl border px-4 text-sm font-bold transition-colors hover:bg-secondary">Open the real business view <ArrowRight className="h-4 w-4" /></Link></div> : <div className="mt-4 rounded-2xl border border-dashed p-6 sm:p-7"><div className="grid h-11 w-11 place-items-center rounded-xl bg-secondary text-primary"><Radio className="h-5 w-5" /></div><p className="mt-4 font-bold">Awaiting the first live record.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">After a merchant sets up a real business, resources, and schedules, QueueSync will surface the available operation here.</p><Button asChild variant="outline" className="mt-5 w-full"><Link href="/merchant">Create a business</Link></Button></div>}</div></div>;
}

function MerchantOperationsPreview() {
  const { isAuthenticated } = useAuth();
  const mine = trpc.businesses.mine.useQuery(undefined, { enabled: isAuthenticated });
  const businessId = mine.data?.[0]?.business.id;
  const queueInput = useMemo(() => ({ businessId: businessId ?? "" }), [businessId]);
  const queue = trpc.queue.listLive.useQuery(queueInput, { enabled: Boolean(businessId) });
  const business = mine.data?.[0]?.business;
  return <section className="soft-rise rounded-[1.5rem] border bg-card/85 p-4 shadow-xl shadow-slate-950/[.03] [animation-delay:130ms]"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Merchant operations</p><p className="mt-1 font-semibold">{business ? business.name : "Your live workspace"}</p></div><span className="rounded-full bg-secondary px-2.5 py-1 text-[11px] font-bold text-muted-foreground">{queue.data?.length ?? 0} live</span></div>{mine.isLoading ? <div className="mt-4 h-20 animate-pulse rounded-xl bg-muted" /> : business ? queue.data?.length ? <div className="mt-4 space-y-2">{queue.data.slice(0, 3).map((item, index) => <div key={item.entry.id} className="flex items-center justify-between gap-3 rounded-xl border bg-background px-3 py-2.5"><div className="min-w-0"><p className="truncate text-sm font-bold">#{index + 1} {item.customer.name || "Customer"}</p><p className="text-xs text-muted-foreground">{item.resource?.name || "Resource assignment pending"}</p></div><Badge variant="secondary" className="shrink-0 capitalize">{item.entry.status.replace("_", " ")}</Badge></div>)}</div> : <div className="mt-4 rounded-xl border border-dashed p-4 text-sm leading-6 text-muted-foreground">No customers are currently in this live queue. New entries will arrive here from the real customer flow.</div> : <div className="mt-4 rounded-xl border border-dashed p-4 text-sm leading-6 text-muted-foreground">Sign in to a merchant account to view a tenant-scoped live operations panel.</div>}<Button asChild variant="outline" className="mt-4 w-full"><Link href="/merchant">Open queue controls <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></section>;
}

function PreviewMetric({ icon: Icon, label, value, detail }: { icon: typeof Building2; label: string; value: string; detail: string }) { return <div className="rounded-2xl border p-4"><Icon className="h-4 w-4 text-primary" /><p className="mt-4 text-xs font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>; }
function SectionEyebrow({ text }: { text: string }) { return <p className="text-sm font-bold text-primary">{text}</p>; }
function ExperienceCard({ eyebrow, icon: Icon, title, detail, actions, href, action }: { eyebrow: string; icon: typeof UsersRound; title: string; detail: string; actions: string[]; href: string; action: string }) { return <article className="rounded-[1.75rem] border bg-card p-5 shadow-sm sm:p-7"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent text-accent-foreground"><Icon className="h-5 w-5" /></span><SectionEyebrow text={eyebrow} /><h2 className="display-font mt-3 text-2xl font-bold tracking-[-.035em]">{title}</h2><p className="mt-3 max-w-lg leading-7 text-muted-foreground">{detail}</p><ul className="mt-5 grid gap-3">{actions.map(item => <li key={item} className="flex items-center gap-2 text-sm font-semibold"><CircleCheck className="h-4 w-4 shrink-0 text-[var(--live)]" />{item}</li>)}</ul><Button asChild variant="outline" className="mt-6 w-full sm:w-auto"><Link href={href}>{action}<ArrowRight className="ml-2 h-4 w-4" /></Link></Button></article>; }
function SyncStep({ icon: Icon, title, detail }: { icon: typeof Radio; title: string; detail: string }) { return <div className="flex min-w-0 gap-4 rounded-2xl border bg-background/60 p-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-accent text-accent-foreground"><Icon className="h-4 w-4" /></span><div><p className="font-bold">{title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{detail}</p></div></div>; }
function BusinessGrid({ loading, items }: { loading: boolean; items: { business: { id: string; name: string; category: string; area: string | null; address: string | null }; resourceCount: number }[] }) { if (loading) return <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-52 animate-pulse rounded-2xl bg-muted" />)}</div>; if (!items.length) return <div className="mt-6 rounded-2xl border border-dashed bg-background/60 p-7 text-center sm:p-10"><Building2 className="mx-auto h-6 w-6 text-primary" /><p className="mt-4 font-bold">No businesses available yet.</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Businesses that join QueueSync will appear here. You can explore the product flow or create the first real business operation.</p><div className="mt-5 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild variant="outline"><Link href="#discover">See how QueueSync works</Link></Button><Button asChild><Link href="/merchant">Create a business</Link></Button></div></div>; return <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(({ business, resourceCount }) => <Link key={business.id} href={`/business/${business.id}`} className="group rounded-2xl border bg-background p-5 shadow-sm transition duration-200 hover:-translate-y-1 hover:border-primary/30 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent text-accent-foreground"><Building2 className="h-5 w-5" /></span><Badge variant="secondary">{business.category}</Badge></div><h3 className="mt-6 truncate font-bold tracking-tight">{business.name}</h3><p className="mt-2 flex min-h-5 items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="h-3.5 w-3.5 shrink-0" />{business.area || business.address || "Location details available in the business view."}</p><div className="mt-5 grid grid-cols-2 gap-3 border-y py-4 text-xs"><div><p className="font-bold text-muted-foreground">RESOURCES</p><p className="mt-1 font-bold text-foreground">{resourceCount}</p></div><div><p className="font-bold text-muted-foreground">QUEUE</p><p className="mt-1 font-bold text-foreground">View live status</p></div></div><span className="mt-5 flex items-center justify-between text-sm font-bold text-primary">View business <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</div>; }
function BrandFooter() { return <Link href="/" className="display-font font-bold text-foreground">Queue<span className="text-primary">Sync</span></Link>; }
