import React, { useMemo, useState } from "react";
import { Link } from "wouter";
import { Activity, ArrowRight, BarChart3, Building2, CalendarCheck, CheckCircle2, ChevronRight, CircleDot, Clock3, Gauge, MapPin, Radio, Search, ShieldCheck, SlidersHorizontal, Sparkles, UsersRound, Zap } from "lucide-react";
import CustomerNav, { HomeFeatures } from "@/components/CustomerNav";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import LiveFlow from "@/components/LiveFlow";
import { useAuth } from "@/_core/hooks/useAuth";
import { MotionItem, MotionReveal, MotionStagger } from "@/components/MotionReveal";

const journey = [
  { number: "01", icon: Search, title: "Find a time", detail: "Discover a real business and its current availability." },
  { number: "02", icon: CalendarCheck, title: "Choose your path", detail: "Reserve a published slot or join the live queue." },
  { number: "03", icon: Radio, title: "Stay informed", detail: "See verified queue movement without refreshing." },
  { number: "04", icon: BarChart3, title: "Operate with context", detail: "Turn service events into useful operational evidence." },
];

const businessTypes = ["Gaming café", "Salon", "Clinic", "Restaurant", "Co-working", "Sports facility"];

export default function Home() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("");
  const [availableOnly, setAvailableOnly] = useState(false);
  const [openNow, setOpenNow] = useState(false);
  const filters = useMemo(() => ({ query: query || undefined, category: category || undefined, availableOnly, openNow }), [query, category, availableOnly, openNow]);
  const businesses = trpc.businesses.list.useQuery(filters);
  const categories = Array.from(new Set((businesses.data ?? []).map(item => item.business.category))).slice(0, 5);
  const featured = businesses.data?.[0];

  return <div className="brand-canvas min-h-screen overflow-x-clip"><CustomerNav /><main>
    <section className="hero-stage relative overflow-hidden"><div className="sync-thread absolute inset-0 opacity-35" /><div className="container relative grid items-center gap-9 py-12 sm:py-16 lg:grid-cols-[minmax(0,1.04fr)_minmax(22rem,.96fr)] lg:gap-14 lg:py-24 xl:py-28">
      <MotionReveal className="min-w-0"><div className="section-kicker">Real-time queue management</div><h1 className="display-font mt-5 max-w-3xl text-[clamp(3rem,8.1vw,6.2rem)] font-bold leading-[.93] tracking-[-.075em]">Make waiting <span className="text-primary">visible.</span><br />Not wasted.</h1><p className="mt-6 max-w-xl text-[clamp(1rem,2.2vw,1.18rem)] leading-8 text-muted-foreground">QueueSync gives people a clearer way to plan local service time and gives businesses an exact, live view of what happens next.</p><div className="mt-5"><LiveFlow /></div><div className="mt-8 grid gap-3 sm:flex sm:flex-wrap"><Button size="lg" className="w-full sm:w-auto" onClick={() => document.getElementById("discover")?.scrollIntoView({ behavior: "smooth", block: "start" })}>Explore businesses <ArrowRight className="ml-1 h-4 w-4" /></Button><Button size="lg" variant="outline" className="w-full sm:w-auto" onClick={() => window.location.assign("/merchant")}>Run your operations <ChevronRight className="ml-1 h-4 w-4" /></Button></div><div className="mt-9"><HomeFeatures /></div></MotionReveal>
      <MotionReveal delay={0.1}><HeroProductWindow featured={featured} /></MotionReveal>
    </div></section>

    <section className="journey-section border-y border-border/70 py-12 sm:py-16"><div className="container"><MotionReveal><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="section-kicker">One connected service loop</div><h2 className="display-font mt-4 max-w-2xl text-[clamp(2rem,4vw,3.4rem)] font-bold leading-[1.02] tracking-[-.055em]">From a customer’s plan to a merchant’s next move.</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">Every screen reads from the same operational record. No simulated queues. No decorative metrics.</p></div></MotionReveal><MotionStagger className="journey-track mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{journey.map(item => <MotionItem key={item.number}><article className="journey-node group h-full rounded-[1.35rem] p-5 transition-transform duration-200 hover:-translate-y-1"><div className="flex items-center justify-between"><span className="text-xs font-extrabold tracking-[.16em] text-primary">{item.number}</span><span className="grid h-9 w-9 place-items-center rounded-xl bg-secondary text-primary transition-transform duration-200 group-hover:rotate-3"><item.icon className="h-4 w-4" /></span></div><h3 className="mt-7 font-bold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.detail}</p></article></MotionItem>)}</MotionStagger></div></section>

    <section className="experience-split container grid gap-5 py-12 sm:py-16 lg:grid-cols-2 lg:gap-7"><MotionReveal><ExperiencePanel eyebrow="Customer experience" icon={UsersRound} title="Know where your time stands." detail="Customers can discover a business, reserve a genuine time slot, and see live queue context without guessing." highlights={["Search actual availability", "Reserve validated time", "Follow real-time queue updates"]} href="/explore" action="Explore customer flow" /></MotionReveal><MotionReveal delay={0.08}><ExperiencePanel eyebrow="Merchant experience" icon={Gauge} title="Operate from a clearer signal." detail="Merchants configure real capacity, progress customers through service, and review activity generated by their own operation." highlights={["Control resources and schedules", "Progress live queue states", "Review record-derived insight"]} href="/merchant" action="Open merchant workspace" /></MotionReveal></section>

    <section className="container pb-12 sm:pb-16"><MotionReveal><div className="event-thread-stage overflow-hidden rounded-[1.8rem]"><div className="grid gap-8 p-6 sm:p-8 lg:grid-cols-[.9fr_1.1fr] lg:p-10"><div><div className="section-kicker">Live synchronization</div><h2 className="display-font mt-4 text-[clamp(2rem,4vw,3.2rem)] font-bold leading-[1.02] tracking-[-.055em]">One queue movement. Every connected view updated.</h2><p className="mt-5 max-w-lg leading-7 text-muted-foreground">QueueSync broadcasts tenant-scoped booking, resource, notification, and queue events. Customer and merchant experiences resolve from the same live state.</p><div className="mt-7 flex items-center gap-3 rounded-2xl border bg-secondary/70 p-4"><span className="signal-orb h-10 w-10 shrink-0"><Radio className="h-4 w-4" /></span><div><p className="text-sm font-bold">Verified state, not a demo timer</p><p className="mt-1 text-xs leading-5 text-muted-foreground">A visual model of the live product contract.</p></div></div></div><SyncDiagram /></div></div></MotionReveal></section>

    <section id="discover" className="container scroll-mt-24 pb-12 sm:pb-16"><MotionReveal><div className="discovery-console rounded-[1.8rem] p-5 sm:p-7 lg:p-9"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="section-kicker">Business discovery</div><h2 className="display-font mt-3 text-[clamp(2rem,4vw,3rem)] font-bold tracking-[-.05em]">Find time that works for you.</h2></div><label className="field-polish flex w-full items-center gap-2 border bg-background/85 px-3 py-2.5 text-sm text-muted-foreground lg:max-w-sm"><Search className="h-4 w-4 shrink-0" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Business, category, or area" className="h-7 min-w-0 border-0 bg-transparent p-0 shadow-none focus-visible:ring-0" /></label></div><div className="mt-6 flex flex-wrap gap-2"><Button size="sm" variant={category === "" ? "default" : "outline"} onClick={() => setCategory("")}>All businesses</Button>{categories.map(item => <Button key={item} size="sm" variant={category === item ? "default" : "outline"} onClick={() => setCategory(item)}>{item}</Button>)}<Button size="sm" variant={availableOnly ? "default" : "outline"} onClick={() => setAvailableOnly(value => !value)}><SlidersHorizontal className="mr-1 h-3.5 w-3.5" />Available now</Button><Button size="sm" variant={openNow ? "default" : "outline"} onClick={() => setOpenNow(value => !value)}><Clock3 className="mr-1 h-3.5 w-3.5" />Open now</Button></div><BusinessGrid loading={businesses.isLoading} items={businesses.data ?? []} /></div></MotionReveal></section>

    <section className="industry-band border-y border-border/70 py-12 sm:py-16"><div className="container"><MotionReveal><div className="section-kicker">Built for local service operations</div><h2 className="display-font mt-4 max-w-2xl text-[clamp(2rem,4vw,3rem)] font-bold tracking-[-.05em]">A calmer system for the moments people normally wait through.</h2><div className="mt-7 flex flex-wrap gap-2.5">{businessTypes.map(type => <span key={type} className="rounded-full border bg-card px-4 py-2 text-sm font-semibold text-muted-foreground shadow-sm">{type}</span>)}</div></MotionReveal></div></section>

    <section className="container py-12 sm:py-16"><MotionReveal><div className="closing-signal relative overflow-hidden rounded-[1.8rem] px-6 py-10 text-primary-foreground sm:px-9 sm:py-12"><div className="absolute -right-12 -top-12 h-52 w-52 rounded-full border-[24px] border-primary-foreground/10" /><div className="relative grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-primary-foreground/70">Ready when your operation is</p><h2 className="display-font mt-3 max-w-2xl text-[clamp(2.2rem,5vw,4rem)] font-bold leading-[.95] tracking-[-.065em]">Make the next wait a clear plan.</h2><p className="mt-5 max-w-xl leading-7 text-primary-foreground/80">Configure a real business, then let QueueSync build the live experience from what actually happens.</p></div><div className="grid gap-3 sm:flex"><Button asChild size="lg" variant="secondary" className="w-full bg-white text-foreground hover:bg-white/90 sm:w-auto"><Link href="/merchant">Set up a business</Link></Button><Button asChild size="lg" variant="outline" className="w-full border-primary-foreground/35 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground sm:w-auto"><Link href="/explore">Explore QueueSync</Link></Button></div></div></div></MotionReveal></section>
  </main><footer className="border-t border-border/70 bg-card/45"><div className="container flex flex-col gap-3 py-7 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><BrandFooter /><p>Real bookings, queues, and operations—kept in sync.</p></div></footer></div>;
}

function HeroProductWindow({ featured }: { featured: { business: { id: string; name: string; category: string; area: string | null; address: string | null }; resourceCount: number } | undefined }) {
  return <div className="hero-window relative overflow-hidden rounded-[1.8rem] p-4 sm:p-5"><div className="absolute inset-x-0 top-0 h-1 bg-primary" /><div className="flex items-center justify-between border-b pb-4"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-primary">Live product window</p><p className="mt-1 text-sm font-bold">Availability is a shared signal.</p></div><span className="inline-flex items-center gap-2 rounded-full border bg-secondary/75 px-2.5 py-1 text-[11px] font-bold text-foreground"><i className="status-dot status-dot-pulse" />Connected</span></div>{featured ? <div className="mt-4"><div className="rounded-[1.25rem] bg-secondary/75 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-muted-foreground">Real business record</p><p className="mt-2 truncate text-xl font-bold">{featured.business.name}</p><p className="mt-1 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="h-3.5 w-3.5" />{featured.business.area || featured.business.address || featured.business.category}</p></div><Badge variant="secondary" className="shrink-0">{featured.business.category}</Badge></div><div className="mt-5 grid grid-cols-2 gap-3"><PreviewMetric icon={Building2} label="Resources" value={`${featured.resourceCount}`} /><PreviewMetric icon={CalendarCheck} label="Customer path" value="Book or join" /></div></div><Link href={`/business/${featured.business.id}`} className="group mt-3 flex min-h-12 items-center justify-between rounded-xl border bg-card px-4 text-sm font-bold transition-all hover:border-primary/40 hover:bg-secondary">Open verified availability <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></div> : <div className="empty-illustration mt-4 rounded-[1.3rem] border border-dashed p-6"><span className="signal-orb h-12 w-12"><Radio className="h-5 w-5" /></span><p className="mt-5 font-bold">Waiting for the first live record.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">When a merchant configures a real business, its operational signal will appear here.</p><Button asChild variant="outline" className="mt-5 w-full"><Link href="/merchant">Create a business</Link></Button></div>}</div>;
}

function PreviewMetric({ icon: Icon, label, value }: { icon: typeof Building2; label: string; value: string }) { return <div className="rounded-xl border bg-card/75 p-3"><Icon className="h-4 w-4 text-primary" /><p className="mt-3 text-[10px] font-extrabold uppercase tracking-[.12em] text-muted-foreground">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>; }

function ExperiencePanel({ eyebrow, icon: Icon, title, detail, highlights, href, action }: { eyebrow: string; icon: typeof UsersRound; title: string; detail: string; highlights: string[]; href: string; action: string }) { return <article className="experience-panel relative h-full overflow-hidden rounded-[1.7rem] p-6 sm:p-8"><span className="signal-orb h-12 w-12"><Icon className="h-5 w-5" /></span><p className="mt-7 text-xs font-extrabold uppercase tracking-[.16em] text-primary">{eyebrow}</p><h2 className="display-font mt-3 max-w-md text-3xl font-bold tracking-[-.045em]">{title}</h2><p className="mt-4 max-w-lg leading-7 text-muted-foreground">{detail}</p><ul className="mt-6 grid gap-3">{highlights.map(item => <li key={item} className="flex items-center gap-2.5 text-sm font-semibold"><CheckCircle2 className="h-4 w-4 shrink-0 text-[var(--live)]" />{item}</li>)}</ul><Button asChild variant="outline" className="mt-7"><Link href={href}>{action}<ArrowRight className="ml-1 h-4 w-4" /></Link></Button></article>; }

function SyncDiagram() { return <div className="event-thread-diagram sync-thread rounded-[1.35rem] border p-4 sm:p-6"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-muted-foreground">The shared event thread</p><div className="mt-5 grid gap-3"><SyncStep icon={UsersRound} label="Customer" detail="Sees an updated position and wait context." tone="bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" /><div className="ml-8 flex items-center gap-3 text-xs font-bold text-primary"><span className="h-px flex-1 bg-primary/25" /><CircleDot className="h-4 w-4" /><span className="h-px flex-1 bg-primary/25" /></div><SyncStep icon={Activity} label="Live operation" detail="A verified queue or resource event is recorded." tone="bg-primary/10 text-primary" /><div className="ml-8 flex items-center gap-3 text-xs font-bold text-primary"><span className="h-px flex-1 bg-primary/25" /><CircleDot className="h-4 w-4" /><span className="h-px flex-1 bg-primary/25" /></div><SyncStep icon={BarChart3} label="Merchant" detail="Uses the same state to make the next decision." tone="bg-blue-500/10 text-blue-700 dark:text-blue-300" /></div></div>; }

function SyncStep({ icon: Icon, label, detail, tone }: { icon: typeof UsersRound; label: string; detail: string; tone: string }) { return <div className="flex min-w-0 items-center gap-4 rounded-2xl border bg-card/90 p-4 shadow-sm"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${tone}`}><Icon className="h-4 w-4" /></span><div className="min-w-0"><p className="font-bold">{label}</p><p className="mt-1 text-sm leading-5 text-muted-foreground">{detail}</p></div></div>; }

function BusinessGrid({ loading, items }: { loading: boolean; items: { business: { id: string; name: string; category: string; area: string | null; address: string | null }; resourceCount: number }[] }) { if (loading) return <div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-56 animate-pulse rounded-[1.35rem] bg-muted" />)}</div>; if (!items.length) return <div className="empty-illustration mt-7 rounded-[1.45rem] border border-dashed bg-secondary/35 p-8 text-center sm:p-10"><span className="signal-orb mx-auto h-14 w-14"><Building2 className="h-5 w-5" /></span><p className="mt-5 font-bold">No businesses match this view.</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Try a different availability filter, or create the first real QueueSync operation.</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild variant="outline"><Link href="#discover">Reset discovery</Link></Button><Button asChild><Link href="/merchant">Create a business</Link></Button></div></div>; return <MotionStagger className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(({ business, resourceCount }) => <MotionItem key={business.id}><Link href={`/business/${business.id}`} className="business-record group block h-full rounded-[1.35rem] p-5 transition-all duration-200 hover:-translate-y-1"><div className="flex items-start justify-between gap-3"><span className="signal-orb h-11 w-11"><Building2 className="h-4 w-4" /></span><Badge variant="secondary">{business.category}</Badge></div><h3 className="mt-7 truncate text-lg font-bold tracking-tight">{business.name}</h3><p className="mt-2 flex min-h-5 items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="h-3.5 w-3.5 shrink-0 text-primary" />{business.area || business.address || "Location details in the business view"}</p><div className="mt-5 grid grid-cols-2 gap-3 border-y py-4 text-xs"><div><p className="font-extrabold tracking-[.11em] text-muted-foreground">RESOURCES</p><p className="mt-1 text-sm font-bold text-foreground">{resourceCount}</p></div><div><p className="font-extrabold tracking-[.11em] text-muted-foreground">QUEUE</p><p className="mt-1 text-sm font-bold text-foreground">Live status</p></div></div><span className="mt-5 flex items-center justify-between text-sm font-bold text-primary">View business <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></Link></MotionItem>)}</MotionStagger>; }

function BrandFooter() { return <Link href="/" className="display-font flex items-center gap-2 font-bold text-foreground"><span className="status-dot" />Queue<span className="text-primary">Sync</span></Link>; }
