import { useCallback, useEffect, useState } from "react";
import { Clock3, Radio, Sparkles, UsersRound } from "lucide-react";
import CustomerNav from "@/components/CustomerNav";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { useRealtime } from "@/hooks/useRealtime";
import { Link } from "wouter";
import LiveFlow from "@/components/LiveFlow";

export default function LiveQueue() {
  const [businessId, setBusinessId] = useState<string | null>(null);
  useEffect(() => setBusinessId(sessionStorage.getItem("queuesync-active-business")), []);
  const queue = trpc.queue.mine.useQuery({ businessId: businessId ?? "" }, { enabled: Boolean(businessId) });
  const invalidate = useCallback(() => { queue.refetch(); }, [queue]);
  useRealtime(businessId ?? undefined, invalidate);
  const snapshot = queue.data;
  return <div className="min-h-screen overflow-x-clip mesh-bg"><CustomerNav /><main className="container max-w-4xl py-8 sm:py-12"><p className="text-sm font-bold text-primary">Live queue</p><h1 className="display-font mt-2 max-w-2xl text-[clamp(2rem,9vw,3.75rem)] font-bold leading-[1.02] tracking-[-.05em]">Your current place in line.</h1><p className="mt-3 max-w-xl leading-7 text-muted-foreground">Your position and estimate are recalculated when real queue or resource events occur—no page refresh is needed.</p>{!businessId ? <QueueEmpty title="No active queue selected." detail="Join a queue from a business page to see your genuine live position here." href="/explore" action="Explore businesses" /> : queue.isLoading ? <div className="mt-6 h-72 animate-pulse rounded-[1.75rem] bg-muted" /> : snapshot ? <section className="mt-6 overflow-hidden rounded-[1.75rem] border bg-card shadow-xl shadow-slate-950/[.04]"><div className="bg-primary px-5 py-5 text-primary-foreground sm:px-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-primary-foreground/70">You are in the queue</p><p className="mt-2 text-[clamp(1.55rem,6vw,2.25rem)] font-bold capitalize">{snapshot.status.replace("_", " ")}</p><p className="mt-2 text-sm text-primary-foreground/80">Your position will update automatically from the live operation.</p></div><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-white/15"><Radio className="h-5 w-5" /></span></div><div className="mt-5"><LiveFlow compact /></div></div><div className="grid gap-px bg-border sm:grid-cols-3"><QueueMetric icon={UsersRound} label="Current position" value={snapshot.position === null ? "—" : `#${snapshot.position}`} detail={snapshot.peopleAhead === 1 ? "1 person ahead" : `${snapshot.peopleAhead} people ahead`} /><QueueMetric icon={Clock3} label="Estimated wait" value={snapshot.estimatedWait.minutes === null ? "—" : `${snapshot.estimatedWait.minutes} min`} detail="Derived from active operations" /><QueueMetric icon={Sparkles} label="Estimate basis" value={snapshot.estimatedWait.basis.replaceAll("_", " ")} detail="Shown transparently" compact /></div><div className="p-5 sm:p-7"><p className="rounded-xl bg-secondary p-4 text-sm leading-6 text-secondary-foreground">{snapshot.estimatedWait.message}</p><p className="mt-4 text-xs font-semibold text-muted-foreground">Updates arrive when a merchant changes the queue or resource state.</p></div></section> : <QueueEmpty title="No active entry for this business." detail="The queue may have ended, or you can join a new live queue from the business page." href={`/business/${businessId}`} action="Open business" />}</main></div>;
}

function QueueMetric({ icon: Icon, label, value, detail, compact = false }: { icon: typeof UsersRound; label: string; value: string; detail: string; compact?: boolean }) { return <div className="bg-card p-5 sm:p-6"><Icon className="h-4 w-4 text-primary" /><p className="mt-4 text-xs font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className={`mt-1 font-bold tracking-tight capitalize ${compact ? "text-lg" : "text-3xl"}`}>{value}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>; }
function QueueEmpty({ title, detail, href, action }: { title: string; detail: string; href: string; action: string }) { return <section className="mt-6 rounded-[1.75rem] border border-dashed bg-card/65 p-7 text-center sm:p-10"><Radio className="mx-auto h-6 w-6 text-primary" /><p className="mt-4 font-semibold">{title}</p><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-muted-foreground">{detail}</p><Button asChild className="mt-5"><Link href={href}>{action}</Link></Button></section>; }
